### ISSUE TITLE
ContextualVersionConflict occurred.

### ISSUE THREAD

**Issue by tagomaru** [polyswarm/contractor#63]
**Describe the bug**
I tried to compile on Mac and Ubuntu, but I got `ContextualVersionConflict` error.

**To Reproduce**
```
(polyswarmvenv) $ python --version
Python 3.6.9
(polyswarmvenv) $ pip --version
pip 19.1.1 from /home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pip (python 3.6)
(polyswarmvenv) $ contractor compile
Traceback (most recent call last):
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.21.0 (/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages), Requirement.parse('requests==2.9.1'), {'ethjsonrpc'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/work/contractor/polyswarmvenv/bin/contractor", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (requests 2.21.0 (/home/ubuntu/work/contractor/polyswarmvenv/lib/python3.6/site-packages), Requirement.parse('requests==2.9.1'), {'ethjsonrpc'})
```

**Expected behavior**
Successfully compiled.

**Additional context**
I commented out [install_requires](https://github.com/polyswarm/contractor/blob/master/setup.py#L18) on `setup.py`, then the compile was done.

I am not sure why this does not occur on [this image](https://github.com/polyswarm/contractor/blob/master/docker/Dockerfile#L1).

**Comment by mrtizmoatwork-psadmin** [comment]
@Rizato can you look into this?
