### ISSUE TITLE
ValueError: {'message': 'invalid transaction v, r, s values', 'code': -32000}

### ISSUE THREAD

**Issue by mjkoo** [polyswarm/contractor#7]
**Describe the bug**

Seems to happen more often on e2e, might be related to geth version (1.8.19 broken locally, 1.8.18 works)

```
Traceback (most recent call last):
  File "/usr/local/bin/contractor", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/contractor/__main__.py", line 70, in deploy
    steps.run(network, deployer)
  File "/usr/local/lib/python3.5/site-packages/contractor/steps/__init__.py", line 49, in run
    step.run(network, deployer)
  File "/usr/local/lib/python3.5/site-packages/contractor/steps/NectarToken.py", line 22, in run
    deployer.deploy(CONTRACT_NAME)
  File "/usr/local/lib/python3.5/site-packages/contractor/deployer.py", line 118, in deploy
    txhash = self.transact(call, txopts)
  File "/usr/local/lib/python3.5/site-packages/contractor/deployer.py", line 132, in transact
    return self.__network.send_transaction(signed_tx)
  File "/usr/local/lib/python3.5/site-packages/contractor/config.py", line 110, in send_transaction
    return self.w3.eth.sendRawTransaction(signed_tx.rawTransaction)
  File "/usr/local/lib/python3.5/site-packages/web3/eth.py", line 274, in sendRawTransaction
    [raw_transaction],
  File "/usr/local/lib/python3.5/site-packages/web3/manager.py", line 112, in request_blocking
    raise ValueError(response["error"])
ValueError: {'message': 'invalid transaction v, r, s values', 'code': -32000}
```

**Comment by mjkoo** [comment]
This is actually due to a misconfiguration of EIP-155 block in priv-testnet which caused transactions in the first few blocks to be parsed with different logic, contracts was not affected due to longer waits before the first transactions.
